### ISSUE TITLE
Gff.hpp:157    ERR| gff missing field 'PortraitId'

### ISSUE THREAD

**Issue by svolpe** [jd28/rollnw#93]
I get the following error when I call Player.from_file("tests/test_data/user/servervault/CDKEY/testsorcpc1.bic"). I originally saw the error when trying to open my characters so I thought I would try the one used by rollnw Character (test_player.py) test case and it had the same issue 

I installed rollnw using pip.
OS: Linux 64bit, Manjaro (Arch Linux based)
Python version: Python 3.12.6
rollnw version: 0.42.dev0

Is this a known issue? If you can point me in the right direction I can try to debug the source code and see what might be going on if its not a known issue.

**Comment by svolpe** [comment]
It is causing the py debugger to exit:
Exception has occurred: RuntimeError
kernel: unable to load object service
  File "/home/shane/dev/rollnw-test/rollnw_test.py", line 3, in <module>
    crt = Player.from_file("tests/test_data/user/servervault/CDKEY/testsorcpc1.bic")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: kernel: unable to load object service

How do I stop it from doing that?

**Comment by jd28** [comment]
Do you have 

```python
import rollnw
rollnw.kernel.start()
```
in your script?

**Comment by svolpe** [comment]
No I did not! That fixed it.  
I can use this to read and edit player character too, correct? 
I've been writing a python/flask based web interface that provides an interface for managing multiple NWN servers via docker images and managing the active players + their characters. I have all of the first part done and working, I'm just now adding in the web interface for editing characters and wanted to use your utility instead of writing my own from ground up.

**Comment by jd28** [comment]
Player is currently read-only since it was missing a few new things, like mentioned above, visual transforms, per part coloring and I didn't want anyone to unintentionally mess up their BICs. Now that I've implemented those saving is the next phase.  From a cursory look I think this project and yours will complement each other quite nicely. Check out some of the [notebooks](https://github.com/jd28/rollnw/tree/main/notebooks) and some of the things you might want to be able to do, I'm working on (but in C++): https://github.com/jd28/arclight?tab=readme-ov-file#creature-view---inventory

**Comment by svolpe** [comment]
There is quite a bit of good information in your notebooks! I will go through all of them next. Is there another way (discord, email, etc.) that I can message you instead of using an issue? After I digest all of your documentation and think about what I might want to integrate into my project I'm sure I will have more questions.
